name: companioneyes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-279.2.beta <4.0.0"

dependencies:
  agora_rtc_engine: ^6.3.0
  animated_custom_dropdown: ^3.0.0
  auto_route: ^7.9.2
  awesome_notifications: ^0.9.3+1
  circle_nav_bar: ^2.0.1+1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.17.9
  firebase_core: ^2.24.2
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_vibrate: ^1.3.0
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.0
  uuid: ^4.4.0
  zego_express_engine: ^3.14.5+2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/ce.json
