name: companioneyes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-279.2.beta <4.0.0"

dependencies:
  animated_custom_dropdown: ^3.0.0
  circle_nav_bar: ^2.0.1+1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  intl_phone_number_input: ^0.7.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  pin_code_fields: ^8.0.1
  provider: ^6.1.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
